name: Run Tests
on: [push, pull_request]
  branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Run tests
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: npm test
      run: npm test
build:
  needs: test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - name: Publish to registry
    uses: elgohr/Publish-Docker-Github-Action@master
    with:
      name: michaelerobertsjr/hello-rio
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      # cache: true # Cache the non changed parts forever.