name: Build PR version

on: 
  pull_request:
    branches-ignore:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Run tests
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: npm test
      run: npm test
